### ISSUE TITLE
Conflict with Caldera Form on WordPress

### ISSUE THREAD

**Issue by chernytan** [dornaweb/product-specifications#10]
Hi, can you help me to see what the issue between this plugin and Caldera form? 
I installed both plugins on my sites and it seems that it's conflict with the Caldera form. Textbox, radio button doesn't work on Caldera form. 

I can't tick or untick the textbox under my Caldera form. Any ideas to solve this? 

![Capture](https://user-images.githubusercontent.com/68673414/88246603-87fba780-cccd-11ea-8d5f-aaf322ccdd0d.PNG)

error found on browser:
![image](https://user-images.githubusercontent.com/68673414/88246660-bbd6cd00-cccd-11ea-80ee-7e7cf1e72d23.png)

**Comment by amiut** [comment]
The Caldera Forms is closed as of April 2022 ([announcement](https://calderaforms.com/2022/04/caldera-forms-closure/)), so providing compatibility doesn't seem reasonable anymore.
