### ISSUE TITLE
مشکل متن در پاراگراف

### ISSUE THREAD

**Issue by abbasranaee** [dornaweb/product-specifications#26]
سلام، در پاراگراف ها بدین صورت نشون میده متون رو و در آپدیت های قبل این مورد نبود. مشکل از کجاست؟

مثلا بدین شمل: از جمله:<br /> 1: سرعت<br /> 2: امنیت<br /> 3: افزایش رتبه<br /> 4:

**Comment by amiut** [comment]
سلام ببخشید متوجه نشدم
ممنون میشم اگه مراحلی که منجر به بروز این باگ میشه رو توضیح بدید.

**Comment by amiut** [comment]
I'm closing this issue as resolved since there were no more replies, please feel free to re-open it or create a new issue if the problem still exists.

**Comment by Behvand** [comment]
Our friend is pointing out that nl2br is not applied; it doesn't move to the next line and displays the text as:

1:سرعت
2:امنیت
3:افزایش رتبه

It shows it as 1: سرعت2: امنیت3: افزایش رتبه

**Comment by amiut** [comment]
Thanks for bringing this back up, the issue is also reported in #40, It will be fixed in the upcoming release
