### ISSUE TITLE
Need Zip for Wordpress Install

### ISSUE THREAD

**Issue by meandrake** [dornaweb/product-specifications#30]
Hi,
Since we don't all have server access and need to install Plugins via Wordpress ADD PLUGIN feature, and this excellent plugin is not availabl eon wordpress repository, is it possible to get a zip file for installation to our site?
Thanks.

**Comment by amiut** [comment]
Hi
Sure, you can downloaded the latest version zip file from [releases page](https://github.com/dornaweb/product-specifications/releases)
