### ISSUE TITLE
do_shortcode() Not working in product page template

### ISSUE THREAD

**Issue by ymsstudios** [dornaweb/product-specifications#4]
I’m trying to add the specs table to a product page template by using the WordPress `do_shortcode()` function but it simply does not work.

Here’s the code I used in my template: `<?php echo do_shortcode('[specs-table]'); ?>`

When I used the same code for different shortcodes such as `<?php echo do_shortcode('[related_products limit="2"]'); ?>` everything worked just fine and when I tried to use just the shortcode `[specs-table]` in the product description it also worked fine – I only have this issue when using `<?php echo do_shortcode('[specs-table]'); ?>` in the product template.

Thanks in advance,
Martin

**Comment by amiut** [comment]
Answered on [Wordpress website](https://wordpress.org/support/topic/do_shortcode-not-working-in-product-page-template/)
