### ISSUE TITLE
Textarea New Line

### ISSUE THREAD

**Issue by The-HopelessGamer** [dornaweb/product-specifications#40]
Hi there,

The attributes that have a Textarea do not display as multiple lines.

If I write this:

"Line One
Line Two"

It outputs as this:

"Line One Line Two".

When I modify the CSS and add "white-space: pre-line;", for some reason, there is a empty line at the top of each textarea before the text that is supposed to be shown. 

Can this be added in a future release please?

**Comment by amiut** [comment]
Thanks for reporting this, this bug is being fixed and will be included in the next release.
