### ISSUE TITLE
I can't find the "Products" section!

### ISSUE THREAD

**Issue by Sheharyar566** [dornaweb/product-specifications#7]
Hello sir! I just downloaded your plugin and started using it.
In your tutorial on the official plugin page, in the "how to use this plugin section", you said something about the "Products" section.
But the thing is I can't find such a section anywhere.
Can you please tell me what am I doing wrong?

Oh! And I haven't installed woocommerce.

Thanks!

**Comment by amiut** [comment]
The plugin works with Woocommerce it is designed for woocommerce products.
