### ISSUE TITLE
I filled the values, use the vertical pipe “|” why it does not work

### ISSUE THREAD

**Issue by gunrose2003** [dornaweb/product-specifications#9]
Hi, I filled the values, use the vertical pipe “|” for example, I inputed the”pink | blue | Red” on the value(attribute file type is “select”), the product page of backend can not separate the “pink” “blue” “red” into 3 options, just show “pink | blue | Red” (only one option), what’s happened?

**Comment by amiut** [comment]
Hi
Options must be separated by with new line, Example:
`
pink
red
blue
`

**Comment by emmalohmus** [comment]
Hello,
i have a similar problem. I copied the "pink red blue" into "select" attribute values, and while it is able to create an array for choosing the default option, it is not able to create an array on the product editing page.

![pilt](https://github.com/user-attachments/assets/08ee46ff-b192-4ca8-b1e3-6bcc660bd535)
